-- 대여 중인 자동차들의 정보(CAR_RENTAL_COMPANY_CAR)
-- 자동차 대여 기록 정보(CAR_RENTAL_COMPANY_RENTAL_HISTORY)
-- 자동차 종류 별 대여 기간(CAR_RENTAL_COMPANY_DISCOUNT_PLAN)

-- 조건
-- 1. 자동차 종류가 '세단', 'SUV'
-- 2. 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능
-- 3. 30일간의 대여 금액이 50만원 이상 200만원 미만
-- 4. 대여 금액(=FEE)을 기준으로 내림차순 정렬
-- 5. 대여 금액이 같은 경우 자동차 종류를 기준으로 오름차순
-- 6. 자동차 종류까지 같은 경우 자동차 ID를 기준으로 내림차순

SELECT CRCC.CAR_ID, CRCC.CAR_TYPE, ROUND(CRCC.DAILY_FEE * 30 * (100 - CRCDP.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CRCC
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP 
        ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE AND CRCDP.DURATION_TYPE = '30일 이상'
WHERE CRCDP.CAR_TYPE IN ('세단', 'SUV') AND
    CRCC.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30'
    )
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CRCC.CAR_TYPE ASC, CRCC.CAR_ID DESC;
    
