-- 회원 정보(USER_INFO)
-- 온라인 상품 판매 정보(ONLINE_SALE)
SELECT YEAR(OS.SALES_DATE) AS YEAR,
       MONTH(OS.SALES_DATE) AS MONTH,
       COUNT(DISTINCT OS.USER_ID) AS PUCHASED_USERS,
       ROUND(COUNT(DISTINCT OS.USER_ID) / (SELECT COUNT(*)
                                            FROM USER_INFO UI
                                            WHERE DATE_FORMAT(UI.JOINED, "%Y") = '2021'), 1) AS PUCHASED_RATIO
FROM USER_INFO UI
INNER JOIN ONLINE_SALE OS ON UI.USER_ID = OS.USER_ID
WHERE DATE_FORMAT(UI.JOINED, "%Y") = '2021'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH